### ISSUE TITLE
Erro ao passar o extraAmount

### ISSUE THREAD

**Issue by eluizbr** [allisson/django-pagseguro2#12]
Alisson,
Estou tendo problemas ao enviar o campo extraAmount....

Estou enviando assim:

PagSeguroItem(id=id,description=descricao,amount=valor,quantity=1,extraAmount=2.35)

e recebo o seguinte erro:

__init__() got an unexpected keyword argument 'extraAmount'

alguma dica?

Obrigado

**Comment by allisson** [comment]
O extraAmount deve ser passado no PagSeguroApi :)

**Comment by eluizbr** [comment]
pode me dar um exemplo?

**Comment by allisson** [comment]
>>> from pagseguro.api import PagSeguroApi
>>> from decimal import Decimal
>>> extra_amount = Decimal('20.00')
>>> sender_email = 'user@email.com'
>>> sender_name = 'Fulano da Silva'
>>> sender_area_code = 83
>>> sender_phone = 11111111
>>> pagseguro_api = PagSeguroApi(reference='id-unico-de-referencia-do-seu-sistema', extraAmount=extra_amount, senderEmail=sender_email, senderName=sender_name, senderAreaCode=sender_area_code, senderPhone=sender_phone)

Esse exemplo tem na documentação, procure por "Passando parâmetros extras na inicialização do PagSeguroApi:" http://django-pagseguro-2.readthedocs.org/pt_BR/1.0.9/tutorial.html#trabalhando-com-a-api-de-checkout

**Comment by eluizbr** [comment]
obrigado....

2015-06-29 22:29 GMT-03:00 Allisson Azevedo <notifications@github.com>:
