### ISSUE TITLE
KeyError 'redirect_url'

### ISSUE THREAD

**Issue by eluizbr** [allisson/django-pagseguro2#13]
Alisson,

Estou tendo um problema estranho aqui... Funciona tudo muito bem no ambiente SANDBOX,
porem quando coloco o email e token de produção e altero a variável PAGSEGURO_SANDBOX = False

recebo o erro ao tentar realizar uma compra:

KeyError at /portabilidade/financeiro/
'redirect_url'

FUNÇÃO

def pagseguro(id,descricao,valor,codigo,taxa):

	compra = PagSeguroItem(id=id,description=descricao,amount=valor,quantity=1)

	pagseguro_api = PagSeguroApi(reference=codigo,extraAmount=taxa)
	pagseguro_api.add_item(compra)
	data = pagseguro_api.checkout()
	url = data['redirect_url']

	return url

Alguma ideia do que pode ser?

Obrigado

**Comment by allisson** [comment]
Verifique o conteúdo do dicionário data, acho que um print data resolve.

**Comment by allisson** [comment]
Apenas para reforçar, se o dicionário não veio com o 'redirect_url', provavelmente foi retornado algum erro da api do pagseguro.

**Comment by eluizbr** [comment]
Obrigado pelo retorno....
O problema era o EMAIL cadastrado no pagseguro.. o mesmo não tinha permissão para venda....

**Comment by allisson** [comment]
:thumbsup:
