### ISSUE TITLE
Cobrança automatica

### ISSUE THREAD

**Issue by eluizbr** [allisson/django-pagseguro2#15]
Allisson,

É possível enviar cobranças automáticas para o cliente?
É possível gerar um boleto e mandar para o email do ciente?

Obrigado pela atençao

**Comment by allisson** [comment]
Olá,

A parte de assinaturas ainda não foi implementada.

Sobre o gerar boleto, eu acredito que isso ocorre no momento que o cliente vai fazer o pagamento no pagseguro.

**Comment by rodrigoimenes** [comment]
@allisson Alguma novidade com os pagamentos recorrentes?
