### ISSUE TITLE
Pagamento transparente

### ISSUE THREAD

**Issue by andersonresende** [allisson/django-pagseguro2#17]
Opa, tudo bom? Eu acabei de implementar o pagamento transparente em um sistema e gostaria de saber se posso adicionar essa funcionalidade ao django-pagseguro2, fazendo um PR.

**Comment by allisson** [comment]
Opa, tudo bom.

Eu posso fazer assim, eu crio um branch só para esses ajustes do pagamento transparente, ai o seu PR eu coloco lá, então pode enviar o PR.

**Comment by andersonresende** [comment]
Entendo, você não tem vontade de incorporar ao master da aplicação ou que dar um boa avaliada no código?

**Comment by allisson** [comment]
Dar uma avaliada e ver se vale a pena incorporar ou se é melhor você criar uma lib só pra checkout transparente :)

**Comment by andersonresende** [comment]
Ok, valeu, cria a branch pra eu começar os trabalhos ;)

**Comment by allisson** [comment]
Criado https://github.com/allisson/django-pagseguro2/tree/checkout-transparente

**Comment by andersonresende** [comment]
Brigadão ;)

**Comment by luanfonceca** [comment]
Tbm tenho interesse no checkout transparente, a quantas anda o código @andersonresende ?

o/

**Comment by andersonresende** [comment]
Opa td bom? Ja esta quase pronto Luan ;)

**Comment by luanfonceca** [comment]
Dá uns commit ai depois o/

**Comment by andersonresende** [comment]
Tranquilo, até domingo ja subo algo ;)

**Comment by luanfonceca** [comment]
Show o/

**Comment by taizarm** [comment]
Tb tenho interesse :) As mudanças ja foram commitadas?

**Comment by andersonresende** [comment]
Podem acompanhar o andamento aqui: https://github.com/allisson/django-pagseguro2/pull/20
Até hoje a noite vou finalizar os dois métodos que faltam e vai ficar faltando apenas a documentação.

**Comment by luanfonceca** [comment]
@andersonresende o chefinho @filipeximenes mandou tu faz né?! kkkkkkkkkkkkkk

**Comment by filipeximenes** [comment]
hahahhahaha eu mandei nada. Eu só passei o recado que tinha uma turma fazendo pressão pra isso sair hahahah

**Comment by andersonresende** [comment]
@luanfonceca Ele chegou me perguntando se eu gostava de trabalhar na vinta. hahahahha

**Comment by luanfonceca** [comment]
KKKKKKKKKKKKKKKK

**Comment by allisson** [comment]
Se eu rejeitar o pull request parece que vamos ter um aumento do desemprego no país :)

**Comment by andersonresende** [comment]
heheheheheh

**Comment by carlosviol** [comment]
Pessoal, vi que o desenvolvimento está bem avançado já... Precisam de alguma ajuda? Posso ajudar? Pretendo usar a API do checkout transparente também :)

Valeu!

**Comment by allisson** [comment]
Acabei de liberar o release 1.1.0 com a contribuição do @andersonresende do pagamento transparente.

**Comment by luanfonceca** [comment]
AEW
