### ISSUE TITLE
RemovedInDjango20Warning

### ISSUE THREAD

**Issue by wsgomes** [allisson/django-pagseguro2#22]
Esse warning já pode ser arrumado numa próxima versão =)

> /env/lib/python2.7/site-packages/pagseguro/models.py:117: RemovedInDjango20Warning: on_delete will be a required arg for ForeignKey in Django 2.0. Set it to models.CASCADE on models and in existing migrations if you want to maintain the current default behavior. See https://docs.djangoproject.com/en/1.9/ref/models/fields/#django.db.models.ForeignKey.on_delete

**Comment by eltermann** [comment]
acredito que #26 irá resolver

**Comment by ranisalt** [comment]
@allisson esse foi resolvido :)
