### ISSUE TITLE
Cobrança Automática (assinatura)

### ISSUE THREAD

**Issue by marcelometal** [allisson/django-pagseguro2#23]
Olá,
vi que o projeto ainda não tem suporte a cobranças automáticas (assinaturas).

Algumas pessoas pediram (#10  e #15) e eu gostaria muito de usar essa funcionalidade. Vou tomar a liberdade de começar a desenvolvê-la. Se por acaso alguem começou, por favor me avise.

Logo eu envio um PR com um trabalho inicial

**Comment by marcelometal** [comment]
Fiz um fork e estou trabalhando na branch 'pre-approvals':
https://github.com/marcelometal/django-pagseguro2/tree/pre-approvals

**Comment by eltermann** [comment]
@marcelometal, vc avançou nisso além dos commits no seu fork?

**Comment by marcelometal** [comment]
Olá @elterman, acredito que não muito (preciso verificar), mas de noite falo com certeza. Você pretende contribuir?

**Comment by eltermann** [comment]
yep! :)

**Comment by marcelometal** [comment]
@eltermann o que tá publicado foi o ponto que parei mesmo... Você pretende continuar, quer dividir algum pedaço?

**Comment by marcelometal** [comment]
@eltermann fiz mais coisas, e abri um PR. Poderia ajudar a testar?

**Comment by thiagolara** [comment]
@marcelometal tudo bem? Em que ponto está esse fork teu? Falta fazer algo? Falta testar? Estou disposto a contribuir se ainda precisar de algo. Eu cheguei a dar uma olhada no código e tem uns FIXME, porém é difícil saber exatamente o que precisa ser corrigido. Aguardo retorno. valeu !

**Comment by marcelometal** [comment]
@thiagolara tá funcionando, teria so ter testar mais a fundo. Você chegou a rodar com o sandbox? Tentar rodar o codigo e fazer as assinaturas usando o sandbox. Os `FIXME` que deixei são mais pra lembrar que poderia refatorar aquele trecho pra deixar o código melhor.
