### ISSUE TITLE
Consulta por código de Referência.

### ISSUE THREAD

**Issue by DanielChrome** [allisson/django-pagseguro2#24]
Não encontrei na documentação se está implementado o método de consulta de transações pelo código de referência conforme relatado no link: https://comunidade.pagseguro.uol.com.br/hc/pt-br/community/posts/220981147-Consulta-por-C%C3%B3digo-de-Refer%C3%AAncia

Minha necessidade é que, ao realizar o check-out, é gerado o código de direcionamento (redirect_url) e posteriormente preciso verificar se foi gerado transação para este pedido para consultar a mesma.

Vi que no Admin foram criados duas opções para o pagseguro [Checkouts e Transações]. Os checkouts estão sendo gerados sem problemas, mas não estão sendo gerado as transações. Há algo que preciso configurar, como os signals por exemplo??

**Comment by ranisalt** [comment]
Pelo que eu entendi a transação é criada assim que o usuário finaliza o processo de checkout no PagSeguro, enquanto que o Checkout é criado antes do processo. Então, se o usuário vai até o Checkout e então cancela ou fecha a página, ele cria o objeto do Checkout, mas não vai criar a Transaction.

Você precisa configurar a URL de callback (as `urlpatterns` como explica [aqui](https://django-pagseguro-2.readthedocs.io/pt_BR/1.1.0/tutorial.html#configuracao)) pra receber as notificações de update do PagSeguro.
