### ISSUE TITLE
PagSeguro Retorno

### ISSUE THREAD

**Issue by rlimaeco** [allisson/django-pagseguro2#28]
Olá me desculpem caso isto não seja uma Issue, pois quando estava integrando o django-pagseguro2 adicionei sua devida url em urls.py e verifiquei que a única url inserida por este módulo era:

`urlpatterns = [
    url(r'^$', receive_notification, name='pagseguro_receive_notification'),
]`

E esta view receive_notification aceita apenas requisições POST, mas no próprio site do pagseguro ele especifica que utiliza método GET. então este é apenas um exemplo no qual devemos fazer e modificar a view para algo do gênero:

`@csrf_exempt
@require_http_methods(['POST', 'GET'])
def receive_notification(request):
    notification_code = request.GET.get('transaction_id', None)
    #notification_type = request.POST.get('notificationType', None) Não especificado no GET e POST
    
    if notification_code:
        pagseguro_api = PagSeguroApi()
        response = pagseguro_api.get_notification(notification_code)

        if response.status_code == 200:
            if six.PY2:
                return HttpResponse(six.b('Notificação recebida com sucesso.'))
            return HttpResponse(six.u('Notificação recebida com sucesso.'))

    if six.PY2:
        return HttpResponse(six.b('Notificação inválida.'), status=400)
    return HttpResponse(six.u('Notificação inválida.'), status=400)`

Estou realizando a integração deste módulo para o Saleor que utiliza a biblioteca django-payments no qual estou criando o PagSeguroProvider para facilitar sua utilização. Ainda estou em dúvidas de como fazer o controle destas notificações uma vez que o único dado que possuo é o transaction_id do PagSeguro. Desde já sou grato pela atenção

**Comment by rlimaeco** [comment]
Sorry my mistake, I was trying to use in localhost hehehe

**Comment by allisson** [comment]
Sem problemas 👍

**Comment by yuribtt** [comment]
não é possível receber notificações em localhost?
