### ISSUE TITLE
Como informar redirectURL individual por pagamento?

### ISSUE THREAD

**Issue by pedrovgp** [allisson/django-pagseguro2#31]
Pela [API](https://dev.pagseguro.uol.com.br/referencia-da-api/api-de-pagamentos-pagseguro#!/ws_pagseguro_uol_com_br/v2_checkout_xml) é possível indicar um parâmetro redirectURL determinando para onde o comprador será redirecionado ao final do fluxo de pagamento.

Não consegui descobrir como passar esse parâmetro usando o django-pagseguro2. Gostaria que, ao final do pagamento, o comprador pudesse voltar ao meu site e consultar diretamente o status do seu pedido.

**Comment by allisson** [comment]
@pedrovgp você pode passar o redirectURL quando for criar uma nova instância do PagSeguroApi.

Exemplo:
```python
pagseguro_api = PagSeguroApi(reference='id-unico-de-referencia-do-seu-sistema', redirectURL='https://meusite.com/compra-feita/id-unico-de-referencia-do-seu-sistema/')
```
