### ISSUE TITLE
Problema ao tentar migrar após instalar o app

### ISSUE THREAD

**Issue by leandrorcamargo** [allisson/django-pagseguro2#32]
Segui os passos de instalação e configuração do tutorial, mas ao tentar dar runserver ou migrate ocorre este erro:

File "/home/user/.local/lib/python3.6/site-packages/pagseguro/migrations/0002_auto_20150506_0220.py", line 71, in Migration
    field=models.ForeignKey(verbose_name='Transa\xe7\xe3o', to='pagseguro.Transaction'),
TypeError: __init__() missing 1 required positional argument: 'on_delete

A versão do python rodando aqui é 3.6.3 no momento.

**Comment by allisson** [comment]
Olá leandrorcamargo, obrigado por avisar, estou fazendo os testes de compatibilidade com o django 2.0 e aviso aqui quando sair uma nova versão corrigindo esse problema.

**Comment by allisson** [comment]
@leandrorcamargo tente novamente usando a versão 2.0.1 :+1:

**Comment by leandrorcamargo** [comment]
O problema foi resolvido mesmo! 
Muito obrigado!!!
