### ISSUE TITLE
noInterestInstallmentQuantity - novo parametro na api

### ISSUE THREAD

**Issue by fcsaneti** [allisson/django-pagseguro2#33]
Fazendo a requisição para pegar o parcelamento sem juros por parte do cliente. 

Passamos a variável maxInstallmentNoInterest: {{ xxx }}, com o valor setado pelo cliente.

Quando enviamos o parametro noInterestInstallmentQuantity obrigatório para o PagSeguro, a api não recebe este parâmetro, existe algum motivo específico, tem um outro meio de passar ou não está implementado?

Ficando:

def set_creditcard_data(self, quantity, value, name, birth_date, cpf, area_code, phone, nointerest=None):

self.params['installmentQuantity'] = quantity
self.params['installmentValue'] = value
self.params['noInterestInstallmentQuantity'] = nointerest
self.params['creditCardHolderName'] = name
self.params['creditCardHolderBirthDate'] = birth_date
self.params['creditCardHolderCPF'] = cpf
self.params['creditCardHolderAreaCode'] = area_code
self.params['creditCardHolderPhone'] = phone

Grato pela ajuda!

**Comment by allisson** [comment]
@fcsaneti o parâmetro no_interest_quantity foi adicionado no método set_creditcard_data na versão 2.0.4 lançada hoje: https://pypi.org/project/django-pagseguro2/2.0.4/
