### ISSUE TITLE
Suporte Django 2.2 e python 3.8

### ISSUE THREAD

**Issue by pedrovgp** [allisson/django-pagseguro2#41]
Existe planos de suportar python 3.8 e Django 2.2? Se não, há alguma alternativa?

**Comment by allisson** [comment]
Olá @pedrovgp, acabei de lançar o major release 3.0.0 com suporte a django 2.2.x e 3.0.x.

Vou atualizar o https://github.com/allisson/django-pagseguro2-example com essa versão asap.

**Comment by pedrovgp** [comment]
Obrigado Allisson! Sugiro atualizar a página principal da documentação também. Foi bom base nela que eu abri o issue.
