### ISSUE TITLE
Erro de decode no processamento da resposta da view de notificação

### ISSUE THREAD

**Issue by andersonbispo** [allisson/django-pagseguro2#7]
Durante o processamento da view receive_notification, no momento em que tenta retornar o HttpResponse com a mensagem de notificação recebida com sucesso, ocorre o seguinte erro em algum middleware:

django.utils.encoding.DjangoUnicodeDecodeError: 'utf-8' codec can't decode byte 0xe7 in position 8: invalid continuation byte. You passed in b'Notifica\xe7\xe3o recebida com sucesso.' (<class 'bytes'>)

E a resposta retorna como erro 500.

**Comment by allisson** [comment]
Olá @andersonbispo, essa mudança que você fez no pull quebrou todos os testes no travis: https://travis-ci.org/allisson/django-pagseguro2/builds/49990144

Eu gostaria de saber mais sobre o sistema que você está recebendo esse erro, a versão do django e do python já é um bom começo :)

**Comment by andersonbispo** [comment]
Olá @allisson, a versão do sistema que estou usando o pagseguro2 está sendo desenvolvida em Python 3.4.1 e Django 1.7.3. Mais tarde irei investigar porque os testes falharam.

**Comment by allisson** [comment]
Eu fiz uma atualização no travis e os testes continuam passando: https://travis-ci.org/allisson/django-pagseguro2/builds/50263327.

O curioso é que testando localmente com o tox, se eu fizer essa modificação do six.b para six.u, todos os testes quebram :)

**Comment by andersonbispo** [comment]
Mas essa versão que está passando é sem meu pull request, não é?

**Comment by allisson** [comment]
Isso, esse último build foi sem seu pull request. Mas pelo que pude ver, ao fazer essa troca os testes quebram.

Eu criei um gist com o resultado aqui: https://gist.github.com/allisson/d974120b5e634bf1890a

**Comment by allisson** [comment]
Opa Anderson,

Desculpa pela demora, eu acabei de fazer o merge do seu pull request, obrigado pela ajuda.

Abraços.
